# Mark Shust's Docker Configuration for Magento
# (https://github.com/markshust/docker-magento)
#
# Version 37.0.2

version: "3"

services:
  app:
    build:
      context: images/nginx/1.18
      args: &args
        UID: 1000
        GID: 1000
        XDEBUG: 'true'
    links:
      - phpfpm
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:cached
      - ./src:/var/www/html
      - sockdata:/sock
      - ssldata:/etc/nginx/certs

  phpfpm: &php
    build:
      context: images/php/7.3
      args: *args
    volumes: *appvolumes
    links:
      - db
    env_file: &env
      - env/magento.env
      - env/db.env

  db:
    image: percona:5.7
    command: --max_allowed_packet=64M
    ports:
      - "3306:3306"
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:5.0-alpine

  # elasticsearch:
  #   image: markoshust/magento-elasticsearch:7.7.1-0
  #   environment:
  #     - "discovery.type=single-node"
  #     - "ES_JAVA_OPTS=-Xms1g -Xmx1g"

  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

  # Disabling cron by default as it uses higher CPU, enable if needed
  cron:
    build: *php
    volumes: *appvolumes
    links:
      - db
    env_file: *env
    user: root
    command: /usr/local/bin/cronstart
    tty: true

volumes:
  appdata:
  dbdata:
  rabbitmqdata:
  sockdata:
  ssldata:
